import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/styles.css";
import Starter from "./Starter/Starter";
import MobileButtons from "./MobileButtons/MobileButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body style={{position:'relative', height: '100vh', display: 'flex', flexDirection: 'row', justifyContent: 'space-between'}} className={inter.className}>
       <Starter/>

        <>
        {children}
        </>
        </body>
    </html>
  );
}
